name:                 testing
version:              0.1.0.0
visibility:           public
id:                   testing-0.1.0.0-inplace
key:                  testing-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    AlberiBinariDiRicerca AlberiGenerici Liste MatriceMedianteQuadTrees
    Matrici Numeri QuadTrees

import-dirs:
    /home/kevinpescarollo/Downloads/Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/testing-0.1.0.0/build

library-dirs:
    /home/kevinpescarollo/Downloads/Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/testing-0.1.0.0/build

library-dirs-static:
    /home/kevinpescarollo/Downloads/Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/testing-0.1.0.0/build

dynamic-library-dirs:
    /home/kevinpescarollo/Downloads/Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/testing-0.1.0.0/build

data-dir:             /home/kevinpescarollo/Downloads/Haskell/.
hs-libraries:         HStesting-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /home/kevinpescarollo/Downloads/Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/testing-0.1.0.0/doc/html/testing/testing.haddock

haddock-html:
    /home/kevinpescarollo/Downloads/Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/testing-0.1.0.0/doc/html/testing
